---
# roles/redis/tasks/main.yml

- name: Install Redis and Webdis
  apt:
    name:
      - redis-server
      - webdis
    state: present
    update_cache: true

- name: Create Redis TLS directory
  file:
    path: /etc/redis/tls
    state: directory
    owner: redis
    group: redis
    mode: '0755'

- name: Generate self-signed cert and key (if not exists)
  command: >
    openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes
    -keyout /etc/redis/tls/redis.key -out /etc/redis/tls/redis.crt
    -subj "/CN=redis.local"
  args:
    creates: /etc/redis/tls/redis.crt

- name: Set permissions on cert files
  file:
    path: "/etc/redis/tls/{{ item }}"
    owner: redis
    group: redis
    mode: "0600"
  loop:
    - redis.crt
    - redis.key

- name: Ensure /run/redis exists for PID file
  file:
    path: /run/redis
    state: directory
    owner: redis
    group: redis
    mode: "0755"

- name: Copy full redis.conf with TLS + password + no persistence
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Reload systemd unit files
    - Restart Redis

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/redis-server.service.d
    state: directory
    mode: "0755"

- name: Override systemd Redis service to support daemonize (Type=forking)
  copy:
    dest: /etc/systemd/system/redis-server.service.d/override.conf
    content: |
      [Service]
      Type=forking
      ExecStart=
      ExecStart=/usr/bin/redis-server /etc/redis/redis.conf
      PIDFile=/run/redis/redis-server.pid
  notify:
    - Reload systemd daemon
    - Reload systemd unit files
    - Restart Redis

- name: Enable Redis on boot
  systemd:
    name: redis-server
    enabled: yes
    state: started

- name: Configure Webdis
  copy:
    dest: /etc/webdis.json
    content: |
      {
        "redis_host": "127.0.0.1",
        "redis_port": 6379,
        "redis_auth": "{{ redis_password }}",
        "http_host": "0.0.0.0",
        "http_port": 6380,
        "https": true,
        "ssl_certificate": "/etc/redis/tls/redis.crt",
        "ssl_private_key": "/etc/redis/tls/redis.key",
        "daemonize": true
      }
  notify: Restart Webdis

- name: Enable Webdis on boot
  systemd:
    name: webdis
    enabled: yes
    state: started
