---
- name: Ensure users are present
  ansible.builtin.user:
    name: "{{ user_present.name }}"
    shell: "{{ user_present.shell | default('/bin/bash') }}"
    state: present
    create_home: true
  loop: "{{ users }}"
  loop_control:
    loop_var: user_present

- name: Ensure Maildir exists in home directory
  ansible.builtin.file:
    path: "/home/{{ user_maildir.name }}/Maildir"
    state: directory
    owner: "{{ user_maildir.name }}"
    group: "{{ user_maildir.name }}"
    mode: "0700"
  loop: "{{ users }}"
  loop_control:
    loop_var: user_maildir
