---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  document-start:
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore: |
  .github/
  roles/grafana/files/
  roles/grafana/templates/
  dns/
