---
- name: Ensure AIDE is installed
  ansible.builtin.package:
    name: aide
    state: present

- name: Ensure /var/log/aide exists
  ansible.builtin.file:
    path: /var/log/aide
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Ensure aide.log permissions are valid
  ansible.builtin.file:
    path: /var/log/aide/aide.log
    state: touch
    owner: root
    group: root
    mode: '0640'
    modification_time: preserve
    access_time: preserve
