---
- name: Reload systemd daemon
  command: systemctl daemon-reexec

- name: Reload systemd unit files
  command: systemctl daemon-reload

- name: Restart Redis
  systemd:
    name: redis-server
    state: restarted

- name: Restart Webdis
  systemd:
    name: webdis
    state: restarted
