---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reexec: true

- name: Reload systemd unit files
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Redis
  systemd:
    name: redis-server
    state: restarted

- name: Restart Webdis
  systemd:
    name: webdis
    state: restarted
