---
- name: Ensure apt-listbugs is uninstalled
  apt:
    name: apt-listbugs
    state: absent
    purge: yes
  ignore_errors: true

- name: Remove apt-listbugs config file 10apt-listbugs
  file:
    path: /etc/apt/apt.conf.d/10apt-listbugs
    state: absent

- name: Remove apt-listbugs config file 99apt-listbugs
  file:
    path: /etc/apt/apt.conf.d/99apt-listbugs
    state: absent

- name: Remove apt-listbugs preferences file
  file:
    path: /etc/apt/preferences.d/apt-listbugs
    state: absent

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Ensure debsums is installed
  apt:
    name: debsums
    state: present

- name: Enable unattended upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Autoremove unused packages
  apt:
    autoremove: yes

- name: Clean APT cache
  apt:
    autoclean: yes
