---
- name: Force disable mpm_prefork by removing symlinks if present
  file:
    path: /etc/apache2/mods-enabled/mpm_prefork.load
    state: absent
  register: prefork_removed
  changed_when: prefork_removed.found is defined and prefork_removed.found
  failed_when: false

- name: Remove mpm_prefork.conf if present
  file:
    path: /etc/apache2/mods-enabled/mpm_prefork.conf
    state: absent
  register: prefork_conf_removed
  changed_when: prefork_conf_removed.found is defined and prefork_conf_removed.found
  failed_when: false

- name: Disable broken qos module if present
  file:
    path: /etc/apache2/mods-enabled/qos.load
    state: absent
  when: ansible_facts['distribution'] == 'Debian' and
        ansible_facts['distribution_version'] is version('10', '>=') and
        ansible_facts['distribution_version'] is version('13', '<') and
        ansible_facts['os_family'] == 'Debian'
  changed_when: false
  failed_when: false

- name: Remove qos.conf if present
  file:
    path: /etc/apache2/mods-enabled/qos.conf
    state: absent
  changed_when: false
  failed_when: false

- name: Ensure qos module package is removed
  apt:
    name: libapache2-mod-qos
    state: absent
  changed_when: false

- name: Disable broken evasive module if present
  file:
    path: /etc/apache2/mods-enabled/evasive.load
    state: absent
  changed_when: false
  failed_when: false

- name: Remove evasive.conf if present
  file:
    path: /etc/apache2/mods-enabled/evasive.conf
    state: absent
  changed_when: false
  failed_when: false

- name: Ensure evasive module package is removed
  apt:
    name: libapache2-mod-evasive
    state: absent
  changed_when: false

- name: Install required Apache modules
  apt:
    name:
      - libapache2-mod-security2
      - ssl-cert
    state: present

- name: Enable commonly needed Apache modules
  apache2_module:
    name: "{{ apache_mod }}"
    state: present
  loop:
    - rewrite
    - headers
    - ssl
    - security2
  loop_control:
    loop_var: apache_mod
  notify: restart apache2

- name: Ensure /etc/apache2 exists
  file:
    path: /etc/apache2
    state: directory
    mode: '0755'

- name: Recursively copy apache2 configuration to /etc/apache2
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/apache2/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: restart apache2

- name: Ensure Apache2 is started and enabled
  service:
    name: apache2
    state: started
    enabled: true
