---
- name: Define list of broken Apache modules and their optional packages
  set_fact:
    broken_apache_modules:
      - name: mpm_prefork
        package: null
      - name: qos
        package: libapache2-mod-qos
      - name: fcgid
        package: libapache2-mod-fcgid
      - name: evasive
        package: libapache2-mod-evasive
      - name: geoip
        package: libapache2-mod-geoip
    required_apache_modules:
      - name: mpm_event
        package: apache2
      - name: php8.2
        package: libapache2-mod-php8.2

- name: Ensure required Apache module packages are installed
  apt:
    name: "{{ required.package }}"
    state: present
  loop: "{{ required_apache_modules }}"
  loop_control:
    loop_var: required
    label: "{{ required.package }}"

- name: Enable required Apache modules
  apache2_module:
    name: "{{ required.name }}"
    state: present
  loop: "{{ required_apache_modules }}"
  loop_control:
    loop_var: required
    label: "{{ required.name }}"
  notify: restart apache2

- name: Disable broken Apache modules by removing .load files
  file:
    path: "/etc/apache2/mods-enabled/{{ mod.name }}.load"
    state: absent
  loop: "{{ broken_apache_modules }}"
  loop_control:
    loop_var: mod
    label: "{{ mod.name }}.load"
  changed_when: false
  failed_when: false

- name: Remove broken Apache modules' .conf files
  file:
    path: "/etc/apache2/mods-enabled/{{ mod.name }}.conf"
    state: absent
  loop: "{{ broken_apache_modules }}"
  loop_control:
    loop_var: mod
    label: "{{ mod.name }}.conf"
  changed_when: false
  failed_when: false

- name: Remove broken Apache module packages if installed
  apt:
    name: "{{ mod.package }}"
    state: absent
  when: mod.package is not none
  loop: "{{ broken_apache_modules }}"
  loop_control:
    loop_var: mod
    label: "{{ mod.package }}"
  changed_when: false

- name: Install required Apache modules
  apt:
    name:
      - libapache2-mod-security2
      - ssl-cert
    state: present

- name: Enable commonly needed Apache modules
  apache2_module:
    name: "{{ apache_mod }}"
    state: present
  loop:
    - rewrite
    - headers
    - ssl
    - security2
  loop_control:
    loop_var: apache_mod
  notify: restart apache2

- name: Ensure /etc/apache2 exists
  file:
    path: /etc/apache2
    state: directory
    mode: '0755'

- name: Recursively copy apache2 configuration to /etc/apache2
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/apache2/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: restart apache2

- name: Ensure Apache2 is started and enabled
  service:
    name: apache2
    state: started
    enabled: true
