---
# Fix MPM conflict first
- name: Attempt to fix broken dpkg state before continuing
  shell: apt-get install -f -y
  changed_when: false
  failed_when: false

- name: Disable mpm_prefork if present to prevent install conflicts
  shell: a2dismod mpm_prefork
  args:
    warn: false
  register: disable_prefork
  changed_when: disable_prefork.rc == 0
  failed_when: false

- name: Enable mpm_event module
  shell: a2enmod mpm_event
  args:
    warn: false
  register: enable_event
  changed_when: enable_event.rc == 0
  failed_when: false

- name: Ensure Apache2 is installed
  apt:
    name: apache2
    state: present
    update_cache: true

- name: Install required Apache modules
  apt:
    name:
      - libapache2-mod-security2
      - ssl-cert
    state: present

- name: Disable broken qos module if present
  file:
    path: /etc/apache2/mods-enabled/qos.load
    state: absent
  when: ansible_facts['distribution'] == 'Debian' and
        ansible_facts['distribution_version'] is version('10', '>=') and
        ansible_facts['distribution_version'] is version('13', '<') and
        ansible_facts['os_family'] == 'Debian'
  changed_when: false

- name: Remove qos module package if installed
  apt:
    name: libapache2-mod-qos
    state: absent
  changed_when: false

- name: Enable commonly needed Apache modules
  apache2_module:
    name: "{{ apache_mod }}"
    state: present
  loop:
    - rewrite
    - headers
    - ssl
    - security2
  loop_control:
    loop_var: apache_mod
  notify: restart apache2

- name: Ensure /etc/apache2 exists
  file:
    path: /etc/apache2
    state: directory
    mode: '0755'

- name: Recursively copy apache2 configuration to /etc/apache2
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/apache2/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: restart apache2

- name: Ensure Apache2 is started and enabled
  service:
    name: apache2
    state: started
    enabled: true
