---
- name: Set cert domain fact from filename
  set_fact:
    cert_domain: "{{ cert.path | basename | regex_replace('\\.conf$', '') }}"

- name: Remove stale renewal file
  file:
    path: "/etc/letsencrypt/renewal/{{ cert_domain }}.conf"
    state: absent
  when: cert_domain not in apache_domains.stdout_lines

- name: Remove stale cert live directory
  file:
    path: "/etc/letsencrypt/live/{{ cert_domain }}"
    state: absent
  when: cert_domain not in apache_domains.stdout_lines

- name: Remove stale cert archive directory
  file:
    path: "/etc/letsencrypt/archive/{{ cert_domain }}"
    state: absent
  when: cert_domain not in apache_domains.stdout_lines
