---
- name: Discover active swap entries (portable fallback)
  become: true
  command: awk 'NR>1 {print $1}' /proc/swaps
  register: active_swap
  changed_when: false

- name: Set fact for discovered swap paths
  set_fact:
    swap_paths: "{{ active_swap.stdout_lines | default([]) }}"

- name: Disable all active swap entries
  become: true
  command: swapoff {{ swap_path }}
  loop: "{{ swap_paths }}"
  loop_control:
    loop_var: swap_path
  ignore_errors: true

- name: Remove swap entries from /etc/fstab
  become: true
  replace:
    path: /etc/fstab
    regexp: '^{{ swap_path | regex_escape }}\s+none\s+swap\s+.*$'
    replace: ''
  loop: "{{ swap_paths }}"
  loop_control:
    loop_var: swap_path
  notify: reload systemd daemon

- name: Remove empty lines from /etc/fstab
  become: true
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^$'

- name: Remove swap files (only if they are files)
  become: true
  file:
    path: "{{ swap_path }}"
    state: absent
  loop: "{{ swap_paths }}"
  loop_control:
    loop_var: swap_path
  when: swap_path.startswith('/')
