---
- name: Install Postfix
  apt:
    name: postfix
    state: present
    update_cache: true

- name: Ensure /etc/postfix exists
  file:
    path: /etc/postfix
    state: directory
    mode: '0755'

- name: Recursively copy Postfix configuration to /etc/postfix
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: Restart postfix

- name: Run postfix check (ignore error if Postfix not fully initialized)
  command: postfix check
  ignore_errors: true
  changed_when: false

# --- Systemd Integration ---

- name: Ensure systemd is reloaded if needed
  command: systemctl daemon-reload
  changed_when: false

- name: Enable postfix@- instance if not already enabled
  command: systemctl is-enabled postfix@-
  register: postfix_instance_enabled
  failed_when: false
  changed_when: false

- name: Enable postfix@- if not enabled
  command: systemctl enable postfix@-
  when: postfix_instance_enabled.rc != 0
  notify: Reload systemd

- name: Start postfix@- if not already running
  command: systemctl is-active postfix@-
  register: postfix_instance_active
  failed_when: false
  changed_when: false

- name: Start postfix@- instance
  command: systemctl start postfix@-
  when: postfix_instance_active.rc != 0

# --- Cert Hook Script ---

- name: Install postfix-updatecerts script from static file
  copy:
    src: postfix-updatecerts.sh
    dest: /usr/bin/postfix-updatecerts
    mode: '0755'
    owner: root
    group: root

# --- Map Builder ---

- name: Define list of postfix map files
  set_fact:
    postfix_maps:
      - { src: "aliases", tool: "postalias" }
      - { src: "bcc_maps", tool: "postmap" }
      - { src: "sender_access", tool: "postmap" }
      - { src: "sender_checks", tool: "postmap" }
      - { src: "sasl_passwd", tool: "postmap" }
      - { src: "client_checks", tool: "postmap" }
      - { src: "header_checks", tool: "postmap" }
      - { src: "recipient_domains", tool: "postmap" }
      - { src: "vhosts", tool: "postmap" }
      - { src: "sasl_passwd", tool: "postmap" }     
      - { src: "helo_access", tool: "postmap" }     
      - { src: "virtualalias.ashtangayoga.ie", tool: "postmap" }
      - { src: "transport.microsoft.db", tool: "postmap" }

- name: Rebuild postfix maps if source file exists
  command: "{{ map_file.tool }} hash:/etc/postfix/{{ map_file.src }}"
  args:
    creates: "/etc/postfix/{{ map_file.src }}.db"
  loop: "{{ postfix_maps }}"
  loop_control:
    loop_var: map_file
  notify: Restart postfix
