---
- name: Install Postfix
  apt:
    name: postfix
    state: present
    update_cache: true

- name: Ensure /etc/postfix exists
  file:
    path: /etc/postfix
    state: directory
    mode: '0755'

- name: Recursively copy Postfix configuration to /etc/postfix
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: Restart postfix

- name: Enable and start Postfix service
  service:
    name: postfix
    enabled: true
    state: started

- name: Ensure postfix-updatecerts script exists with correct content and is executable
  copy:
    dest: /usr/bin/postfix-updatecerts
    mode: '0755'
    owner: root
    group: root
    content: |
      #!/bin/bash
      rm -rvf /etc/postfix/certs/*
      cd /etc/letsencrypt/live
      rm /etc/postfix/sni
      touch /etc/postfix/sni
      for X in `ls | grep -v 'READ\|0001'`; do 
          domain=$(echo $X | sed 's/www\.//')
          echo $domain
          if [ ! -d "/etc/postfix/certs/$domain" ]; then
              mkdir -vp /etc/postfix/certs/$domain
              cat $X/privkey.pem > /etc/postfix/certs/$domain/chain.pem
              cat $X/fullchain.pem >> /etc/postfix/certs/$domain/chain.pem
              echo "$domain /etc/postfix/certs/$domain/chain.pem" >> /etc/postfix/sni
          fi
      done
      /usr/sbin/postmap -F hash:/etc/postfix/sni
      /bin/systemctl restart postfix
