---
- name: Ensure iptables-persistent is installed
  apt:
    name: iptables-persistent
    state: present
    update_cache: true

- name: Define iptables command variants
  set_fact:
    iptables_cmds:
      - iptables
      - ip6tables

- name: Ensure ANSIBLE_INPUT chain exists for iptables
  command: iptables -N ANSIBLE_INPUT
  register: create_ansible_input_v4
  failed_when: false
  changed_when: create_ansible_input_v4.rc == 0

- name: Ensure ANSIBLE_OUTPUT chain exists for iptables
  command: iptables -N ANSIBLE_OUTPUT
  register: create_ansible_output_v4
  failed_when: false
  changed_when: create_ansible_output_v4.rc == 0

- name: Ensure ANSIBLE_INPUT chain exists for ip6tables
  command: ip6tables -N ANSIBLE_INPUT
  register: create_ansible_input_v6
  failed_when: false
  changed_when: create_ansible_input_v6.rc == 0

- name: Ensure ANSIBLE_OUTPUT chain exists for ip6tables
  command: ip6tables -N ANSIBLE_OUTPUT
  register: create_ansible_output_v6
  failed_when: false
  changed_when: create_ansible_output_v6.rc == 0

- name: Ensure INPUT jumps to ANSIBLE_INPUT (iptables)
  command: iptables -C INPUT -j ANSIBLE_INPUT
  register: check_jump_input_v4
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_INPUT if missing (iptables)
  command: iptables -I INPUT 1 -j ANSIBLE_INPUT
  when: check_jump_input_v4.rc != 0

- name: Ensure OUTPUT jumps to ANSIBLE_OUTPUT (iptables)
  command: iptables -C OUTPUT -j ANSIBLE_OUTPUT
  register: check_jump_output_v4
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_OUTPUT if missing (iptables)
  command: iptables -I OUTPUT 1 -j ANSIBLE_OUTPUT
  when: check_jump_output_v4.rc != 0

- name: Ensure INPUT jumps to ANSIBLE_INPUT (ip6tables)
  command: ip6tables -C INPUT -j ANSIBLE_INPUT
  register: check_jump_input_v6
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_INPUT if missing (ip6tables)
  command: ip6tables -I INPUT 1 -j ANSIBLE_INPUT
  when: check_jump_input_v6.rc != 0

- name: Ensure OUTPUT jumps to ANSIBLE_OUTPUT (ip6tables)
  command: ip6tables -C OUTPUT -j ANSIBLE_OUTPUT
  register: check_jump_output_v6
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_OUTPUT if missing (ip6tables)
  command: ip6tables -I OUTPUT 1 -j ANSIBLE_OUTPUT
  when: check_jump_output_v6.rc != 0

- name: Get current ANSIBLE_INPUT rules
  command: iptables -S ANSIBLE_INPUT
  register: current_ansible_input_rules

- name: Get current ANSIBLE_OUTPUT rules
  command: iptables -S ANSIBLE_OUTPUT
  register: current_ansible_output_rules

- name: Get current ANSIBLE_INPUT rules (IPv6)
  command: ip6tables -S ANSIBLE_INPUT
  register: current_ansible_input_v6_rules

- name: Get current ANSIBLE_OUTPUT rules (IPv6)
  command: ip6tables -S ANSIBLE_OUTPUT
  register: current_ansible_output_v6_rules

- name: Build expected INPUT rules
  set_fact:
    expected_input_rule_lines: >-
      {{
        ansible_input_rules | map('iptables_build_rule', 'ANSIBLE_INPUT') | list
      }}

- name: Build expected OUTPUT rules
  set_fact:
    expected_output_rule_lines: >-
      {{
        ansible_output_rules | map('iptables_build_rule', 'ANSIBLE_OUTPUT') | list
      }}

- name: Remove extra ANSIBLE_INPUT rules (iptables)
  shell: "iptables {{ rule | regex_replace('^-A', '-D') }}"
  loop: "{{ current_ansible_input_rules.stdout_lines | difference(expected_input_rule_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_INPUT')
  failed_when: false

- name: Add missing ANSIBLE_INPUT rules (iptables)
  shell: "iptables {{ rule }}"
  loop: "{{ expected_input_rule_lines | difference(current_ansible_input_rules.stdout_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_INPUT')
  failed_when: false

- name: Remove extra ANSIBLE_INPUT rules (ip6tables)
  shell: "ip6tables {{ rule | regex_replace('^-A', '-D') }}"
  loop: "{{ current_ansible_input_v6_rules.stdout_lines | difference(expected_input_rule_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_INPUT')
  failed_when: false

- name: Add missing ANSIBLE_INPUT rules (ip6tables)
  shell: "ip6tables {{ rule }}"
  loop: "{{ expected_input_rule_lines | difference(current_ansible_input_v6_rules.stdout_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_INPUT')
  failed_when: false

- name: Remove extra ANSIBLE_OUTPUT rules (iptables)
  shell: "iptables {{ rule | regex_replace('^-A', '-D') }}"
  loop: "{{ current_ansible_output_rules.stdout_lines | difference(expected_output_rule_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_OUTPUT')
  failed_when: false

- name: Add missing ANSIBLE_OUTPUT rules (iptables)
  shell: "iptables {{ rule }}"
  loop: "{{ expected_output_rule_lines | difference(current_ansible_output_rules.stdout_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_OUTPUT')

- name: Remove extra ANSIBLE_OUTPUT rules (ip6tables)
  shell: "ip6tables {{ rule | regex_replace('^-A', '-D') }}"
  loop: "{{ current_ansible_output_v6_rules.stdout_lines | difference(expected_output_rule_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_OUTPUT')
  failed_when: false

- name: Add missing ANSIBLE_OUTPUT rules (ip6tables)
  shell: "ip6tables {{ rule }}"
  loop: "{{ expected_output_rule_lines | difference(current_ansible_output_v6_rules.stdout_lines) }}"
  loop_control:
    loop_var: rule
  when: rule is search('-A ANSIBLE_OUTPUT')

- name: Prune unmanaged INPUT rules (iptables)
  shell: |
    iptables -S INPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_INPUT' | grep '\-A INPUT' | while read rule; do
      iptables $(echo "$rule" | sed 's/^-A/-D/')
    done
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: Prune unmanaged INPUT rules (ip6tables)
  shell: |
    ip6tables -S INPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_INPUT' | grep '\-A INPUT' | while read rule; do
      ip6tables $(echo "$rule" | sed 's/^-A/-D/')
    done
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: Prune unmanaged OUTPUT rules (iptables)
  shell: |
    iptables -S OUTPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_OUTPUT' | grep '\-A OUTPUT' | while read rule; do
      iptables $(echo "$rule" | sed 's/^-A/-D/')
    done
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: Prune unmanaged OUTPUT rules (ip6tables)
  shell: |
    ip6tables -S OUTPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_OUTPUT' | grep '\-A OUTPUT' | while read rule; do
      ip6tables $(echo "$rule" | sed 's/^-A/-D/')
    done
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: Ensure logging rule exists in ANSIBLE_OUTPUT
  shell: 'iptables -C ANSIBLE_OUTPUT -m conntrack --ctstate NEW -j LOG --log-prefix "IPT-OUTPUT: " --log-level 4 || iptables -I ANSIBLE_OUTPUT 1 -m conntrack --ctstate NEW -j LOG --log-prefix "IPT-OUTPUT: " --log-level 4'
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: Get current iptables policies (IPv4)
  command: iptables -S
  register: iptables_v4_policies
  changed_when: false

- name: Get current ip6tables policies (IPv6)
  command: ip6tables -S
  register: ip6tables_v6_policies
  changed_when: false

- name: Set INPUT policy to DROP (iptables)
  command: iptables -P INPUT DROP
  when: iptables_v4_policies is defined and "'-P INPUT DROP' not in iptables_v4_policies.stdout_lines"
  changed_when: false

- name: Set FORWARD policy to DROP (iptables)
  command: iptables -P FORWARD DROP
  when: iptables_v4_policies is defined and "'-P FORWARD DROP' not in iptables_v4_policies.stdout_lines"
  changed_when: false

- name: Set OUTPUT policy to ACCEPT (iptables)
  command: iptables -P OUTPUT ACCEPT
  when: iptables_v4_policies is defined and "'-P OUTPUT ACCEPT' not in iptables_v4_policies.stdout_lines"
  changed_when: false

- name: Set INPUT policy to DROP (ip6tables)
  command: ip6tables -P INPUT DROP
  when: ip6tables_v6_policies is defined and "'-P INPUT DROP' not in ip6tables_v6_policies.stdout_lines"
  changed_when: false

- name: Set FORWARD policy to DROP (ip6tables)
  command: ip6tables -P FORWARD DROP
  when: ip6tables_v6_policies is defined and "'-P FORWARD DROP' not in ip6tables_v6_policies.stdout_lines"
  changed_when: false

- name: Set OUTPUT policy to ACCEPT (ip6tables)
  command: ip6tables -P OUTPUT ACCEPT
  when: ip6tables_v6_policies is defined and "'-P OUTPUT ACCEPT' not in ip6tables_v6_policies.stdout_lines"
  changed_when: false

- name: Save iptables rules to /etc/iptables/rules.v4 if changed
  copy:
    content: "{{ iptables_v4_rules.stdout }}"
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0644'
  changed_when: false
  when: >
    (create_ansible_input_v4 is defined and create_ansible_input_v4.changed) or
    (create_ansible_output_v4 is defined and create_ansible_output_v4.changed) or
    (input_policy_v4 is defined and input_policy_v4.changed) or
    (forward_policy_v4 is defined and forward_policy_v4.changed) or
    (output_policy_v4 is defined and output_policy_v4.changed)

- name: Save ip6tables rules to /etc/iptables/rules.v6 if changed
  copy:
    content: "{{ iptables_v6_rules.stdout }}"
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: '0644'
  changed_when: false
  when: >
    (create_ansible_input_v6 is defined and create_ansible_input_v6.changed) or
    (create_ansible_output_v6 is defined and create_ansible_output_v6.changed) or
    (input_policy_v6 is defined and input_policy_v6.changed) or
    (forward_policy_v6 is defined and forward_policy_v6.changed) or
    (output_policy_v6 is defined and output_policy_v6.changed)
