---
- name: Ensure iptables-persistent is installed
  apt:
    name: iptables-persistent
    state: present
    update_cache: true

- name: Define iptables command variants
  set_fact:
    iptables_cmds:
      - iptables
      - ip6tables

- name: Ensure ANSIBLE_INPUT chain exists for iptables
  command: iptables -N ANSIBLE_INPUT
  register: create_ansible_input_v4
  failed_when: false
  changed_when: create_ansible_input_v4.rc == 0

- name: Ensure ANSIBLE_OUTPUT chain exists for iptables
  command: iptables -N ANSIBLE_OUTPUT
  register: create_ansible_output_v4
  failed_when: false
  changed_when: create_ansible_output_v4.rc == 0

- name: Ensure ANSIBLE_INPUT chain exists for ip6tables
  command: ip6tables -N ANSIBLE_INPUT
  register: create_ansible_input_v6
  failed_when: false
  changed_when: create_ansible_input_v6.rc == 0

- name: Ensure ANSIBLE_OUTPUT chain exists for ip6tables
  command: ip6tables -N ANSIBLE_OUTPUT
  register: create_ansible_output_v6
  failed_when: false
  changed_when: create_ansible_output_v6.rc == 0

- name: Ensure INPUT jumps to ANSIBLE_INPUT (iptables)
  command: iptables -C INPUT -j ANSIBLE_INPUT
  register: check_jump_input_v4
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_INPUT if missing (iptables)
  command: iptables -I INPUT 1 -j ANSIBLE_INPUT
  when: check_jump_input_v4.rc != 0

- name: Ensure OUTPUT jumps to ANSIBLE_OUTPUT (iptables)
  command: iptables -C OUTPUT -j ANSIBLE_OUTPUT
  register: check_jump_output_v4
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_OUTPUT if missing (iptables)
  command: iptables -I OUTPUT 1 -j ANSIBLE_OUTPUT
  when: check_jump_output_v4.rc != 0

- name: Ensure INPUT jumps to ANSIBLE_INPUT (ip6tables)
  command: ip6tables -C INPUT -j ANSIBLE_INPUT
  register: check_jump_input_v6
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_INPUT if missing (ip6tables)
  command: ip6tables -I INPUT 1 -j ANSIBLE_INPUT
  when: check_jump_input_v6.rc != 0

- name: Ensure OUTPUT jumps to ANSIBLE_OUTPUT (ip6tables)
  command: ip6tables -C OUTPUT -j ANSIBLE_OUTPUT
  register: check_jump_output_v6
  failed_when: false
  changed_when: false

- name: Insert jump to ANSIBLE_OUTPUT if missing (ip6tables)
  command: ip6tables -I OUTPUT 1 -j ANSIBLE_OUTPUT
  when: check_jump_output_v6.rc != 0

- name: Get current ANSIBLE_INPUT rules
  command: iptables -S ANSIBLE_INPUT
  register: current_ansible_input_rules

- name: Get current ANSIBLE_OUTPUT rules
  command: iptables -S ANSIBLE_OUTPUT
  register: current_ansible_output_rules

- name: Get current ANSIBLE_INPUT rules (IPv6)
  command: ip6tables -S ANSIBLE_INPUT
  register: current_ansible_input_v6_rules

- name: Get current ANSIBLE_OUTPUT rules (IPv6)
  command: ip6tables -S ANSIBLE_OUTPUT
  register: current_ansible_output_v6_rules

- name: Manually build expected rule strings for INPUT
  set_fact:
    expected_input_rule_lines: >-
      {{ ansible_input_rules | map('dict2items') | map('map', attribute='key') | list | zip(ansible_input_rules | map('dict2items') | map('map', attribute='value') | list) | map('zip') | map('map', 'join', ' ') | map('join', ' ') | map('regex_replace', '^', '-A ANSIBLE_INPUT ') | list }}

- name: Manually build expected rule strings for OUTPUT
  set_fact:
    expected_output_rule_lines: >-
      {{ ansible_output_rules | map('dict2items') | map('map', attribute='key') | list | zip(ansible_output_rules | map('dict2items') | map('map', attribute='value') | list) | map('zip') | map('map', 'join', ' ') | map('join', ' ') | map('regex_replace', '^', '-A ANSIBLE_OUTPUT ') | list }}

- name: Remove extra ANSIBLE_INPUT rules (iptables)
  shell: "iptables {{ item.replace('-A', '-D') }}"
  loop: "{{ current_ansible_input_rules.stdout_lines | difference(expected_input_rule_lines) }}"
  when: item is search('-A ANSIBLE_INPUT')

- name: Add missing ANSIBLE_INPUT rules (iptables)
  shell: "iptables {{ item }}"
  loop: "{{ expected_input_rule_lines | difference(current_ansible_input_rules.stdout_lines) }}"
  when: item is search('-A ANSIBLE_INPUT')

- name: Remove extra ANSIBLE_INPUT rules (ip6tables)
  shell: "ip6tables {{ item.replace('-A', '-D') }}"
  loop: "{{ current_ansible_input_v6_rules.stdout_lines | difference(expected_input_rule_lines) }}"
  when: item is search('-A ANSIBLE_INPUT')

- name: Add missing ANSIBLE_INPUT rules (ip6tables)
  shell: "ip6tables {{ item }}"
  loop: "{{ expected_input_rule_lines | difference(current_ansible_input_v6_rules.stdout_lines) }}"
  when: item is search('-A ANSIBLE_INPUT')

- name: Remove extra ANSIBLE_OUTPUT rules (iptables)
  shell: "iptables {{ item.replace('-A', '-D') }}"
  loop: "{{ current_ansible_output_rules.stdout_lines | difference(expected_output_rule_lines) }}"
  when: item is search('-A ANSIBLE_OUTPUT')

- name: Add missing ANSIBLE_OUTPUT rules (iptables)
  shell: "iptables {{ item }}"
  loop: "{{ expected_output_rule_lines | difference(current_ansible_output_rules.stdout_lines) }}"
  when: item is search('-A ANSIBLE_OUTPUT')

- name: Remove extra ANSIBLE_OUTPUT rules (ip6tables)
  shell: "ip6tables {{ item.replace('-A', '-D') }}"
  loop: "{{ current_ansible_output_v6_rules.stdout_lines | difference(expected_output_rule_lines) }}"
  when: item is search('-A ANSIBLE_OUTPUT')

- name: Add missing ANSIBLE_OUTPUT rules (ip6tables)
  shell: "ip6tables {{ item }}"
  loop: "{{ expected_output_rule_lines | difference(current_ansible_output_v6_rules.stdout_lines) }}"
  when: item is search('-A ANSIBLE_OUTPUT')

- name: Prune unmanaged INPUT rules (iptables)
  shell: |
    iptables -S INPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_INPUT' | grep '\-A INPUT' | while read rule; do
      iptables ${rule/-A/-D}
    done
  changed_when: false

- name: Prune unmanaged INPUT rules (ip6tables)
  shell: |
    ip6tables -S INPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_INPUT' | grep '\-A INPUT' | while read rule; do
      ip6tables ${rule/-A/-D}
    done
  changed_when: false

- name: Prune unmanaged OUTPUT rules (iptables)
  shell: |
    iptables -S OUTPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_OUTPUT' | grep '\-A OUTPUT' | while read rule; do
      iptables ${rule/-A/-D}
    done
  changed_when: false

- name: Prune unmanaged OUTPUT rules (ip6tables)
  shell: |
    ip6tables -S OUTPUT | grep -v 'DOCKER\|f2b\|ANSIBLE_OUTPUT' | grep '\-A OUTPUT' | while read rule; do
      ip6tables ${rule/-A/-D}
    done
  changed_when: false

- name: Set INPUT policy to DROP (iptables)
  command: iptables -P INPUT DROP
  register: input_policy_v4
  changed_when: input_policy_v4.rc == 0

- name: Set FORWARD policy to DROP (iptables)
  command: iptables -P FORWARD DROP
  register: forward_policy_v4
  changed_when: forward_policy_v4.rc == 0

- name: Set OUTPUT policy to ACCEPT (iptables)
  command: iptables -P OUTPUT ACCEPT
  register: output_policy_v4
  changed_when: output_policy_v4.rc == 0

- name: Set INPUT policy to DROP (ip6tables)
  command: ip6tables -P INPUT DROP
  register: input_policy_v6
  changed_when: input_policy_v6.rc == 0

- name: Set FORWARD policy to DROP (ip6tables)
  command: ip6tables -P FORWARD DROP
  register: forward_policy_v6
  changed_when: forward_policy_v6.rc == 0

- name: Set OUTPUT policy to ACCEPT (ip6tables)
  command: ip6tables -P OUTPUT ACCEPT
  register: output_policy_v6
  changed_when: output_policy_v6.rc == 0
