---
- name: Ensure iptables-persistent is installed
  apt:
    name: iptables-persistent
    state: present
    update_cache: true

- name: Slurp live iptables rules from the system
  slurp:
    src: "{{ iptables_rules_path }}"
  register: live_rules
  ignore_errors: true

- name: Load reference rules file from role (local)
  set_fact:
    reference_rules_content: "{{ lookup('file', role_path + '/files/' + iptables_rules_file) }}"

- name: Decode and strip comment/Fail2Ban lines from live iptables rules
  set_fact:
    live_rules_cleaned: >-
      {{
        (live_rules.content | default('Cg==') | b64decode).split('\n')
        | reject("match", "^#")
        | reject("match", "^$")
        | reject("search", "^:f2b-")
        | reject("search", "^-A f2b-")
        | reject("search", "^-A INPUT.*f2b-")
        | join('\n')
      }}

- name: Decode and strip comment/Fail2Ban lines from reference iptables rules
  set_fact:
    reference_rules_cleaned: >-
      {{
        reference_rules_content.split('\n')
        | reject("match", "^#")
        | reject("match", "^$")
        | reject("search", "^:f2b-")
        | reject("search", "^-A f2b-")
        | reject("search", "^-A INPUT.*f2b-")
        | join('\n')
      }}

- name: Set flag if iptables rules differ
  set_fact:
    rules_differ: "{{ live_rules_cleaned != reference_rules_cleaned }}"

- name: Copy new iptables rules if they differ
  copy:
    src: "{{ iptables_rules_file }}"
    dest: "{{ iptables_rules_path }}"
    owner: root
    group: root
    mode: '0644'
  when: rules_differ

- name: Restore iptables rules from saved file
  shell: iptables-restore < "{{ iptables_rules_path }}"
  when: rules_differ
  changed_when: false

- name: Slurp live ip6tables rules from the system
  slurp:
    src: "{{ ip6tables_rules_path }}"
  register: live_rules_v6
  ignore_errors: true

- name: Load reference ip6tables rules file from role (local)
  set_fact:
    reference_rules_v6_content: "{{ lookup('file', role_path + '/files/' + ip6tables_rules_file) }}"

- name: Decode and strip comment/Fail2Ban lines from live ip6tables rules
  set_fact:
    live_rules_v6_cleaned: >-
      {{
        (live_rules_v6.content | default('Cg==') | b64decode).split('\n')
        | reject("match", "^#")
        | reject("match", "^$")
        | reject("search", "^:f2b-")
        | reject("search", "^-A f2b-")
        | reject("search", "^-A INPUT.*f2b-")
        | join('\n')
      }}

- name: Decode and strip comment/Fail2Ban lines from reference ip6tables rules
  set_fact:
    reference_rules_v6_cleaned: >-
      {{
        reference_rules_v6_content.split('\n')
        | reject("match", "^#")
        | reject("match", "^$")
        | reject("search", "^:f2b-")
        | reject("search", "^-A f2b-")
        | reject("search", "^-A INPUT.*f2b-")
        | join('\n')
      }}

- name: Set flag if ip6tables rules differ
  set_fact:
    rules_v6_differ: "{{ live_rules_v6_cleaned != reference_rules_v6_cleaned }}"

- name: Copy new ip6tables rules if they differ
  copy:
    src: "{{ ip6tables_rules_file }}"
    dest: "{{ ip6tables_rules_path }}"
    owner: root
    group: root
    mode: '0644'
  when: rules_v6_differ

- name: Restore ip6tables rules from saved file
  shell: ip6tables-restore < "{{ ip6tables_rules_path }}"
  when: rules_v6_differ
  changed_when: false
