---
- name: Ensure iptables-persistent is installed
  apt:
    name: iptables-persistent
    state: present
    update_cache: true

- name: Deploy iptables management script
  copy:
    src: manage_iptables.py
    dest: /usr/local/bin/manage_iptables.py
    mode: '0750'

- name: Render iptables rules YAML from host_vars
  copy:
    dest: /etc/ansible/iptables.yml
    content: "{{ iptables | to_nice_yaml(indent=2) }}"
    mode: '0640'

- name: Execute iptables management script
  command: /usr/bin/python3 /usr/local/bin/manage_iptables.py
  changed_when: false
