---
- name: Install postsrsd
  apt:
    name: postsrsd
    state: present
    update_cache: true

- name: Recursively copy postsrsd configuration to /etc
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: Restart postsrsd

- name: Update postsrsd config
  copy:
    src: "{{ role_path }}/files/postsrsd"
    dest: "/etc/default/postsrsd"
    owner: root
    group: root
    mode: '0644'

- name: Enable and start postsrsd service
  service:
    name: postsrsd
    enabled: true
    state: started
