---
- name: Create logrotate config files
  template:
    src: logrotate.conf.j2
    dest: "/etc/logrotate.d/{{ logcfg.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ logrotate_configs }}"
  loop_control:
    loop_var: logcfg

- name: Find all existing logrotate.d files
  find:
    paths: /etc/logrotate.d
    file_type: file
  register: existing_logrotate_files

- name: Delete logrotate configs not in managed list
  file:
    path: "{{ oldfile.path }}"
    state: absent
  loop: "{{ existing_logrotate_files.files }}"
  loop_control:
    loop_var: oldfile
  when: oldfile.path | basename not in logrotate_configs | map(attribute='name') | list
