---
- name: Reload Auditd Rules
  command: augenrules --load

- name: Restart Sysstat
  service:
    name: sysstat
    state: restarted

- name: Restart Auditd
  systemd:
    name: auditd
    state: restarted

- name: Restart Sysstat Timers
  systemd:
    name: "{{ sysstat_timer }}"
    state: restarted
  loop:
    - sysstat-collect.timer
    - sysstat-summary.timer
  loop_control:
    loop_var: sysstat_timer
