---
php_fpm_package: php8.2-fpm
php_fpm_service: php8.2-fpm
php_fpm_conf_dir: /etc/php/8.2/fpm
php_fpm_conf_file: "{{ php_fpm_conf_dir }}/php-fpm.conf"
php_fpm_pool_file: "{{ php_fpm_conf_dir }}/pool.d/www.conf"
