---
- name: Install OpenDKIM
  apt:
    name: opendkim
    state: present

- name: Copy opendkim.conf to /etc
  copy:
    src: "{{ role_path }}/files/opendkim.conf"
    dest: /etc/opendkim.conf
    owner: root
    group: root
    mode: preserve
  notify: Restart opendkim

- name: Recursively copy DKIM keys to /etc/dkimkeys
  copy:
    src: "{{ role_path }}/files/dkimkeys/"
    dest: /etc/dkimkeys/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: Restart opendkim

- name: Update opendkim keytable
  template:
    src: KeyTable.j2
    dest: /etc/dkimkeys/KeyTable
    owner: root
    group: root
    mode: '0644'
  notify: Restart opendkim

- name: Update opendkim SigningTable
  template:
    src: SigningTable.j2
    dest: /etc/dkimkeys/SigningTable
    owner: root
    group: root
    mode: '0644'
  notify: Restart opendkim

- name: Update opendkim TrustedHosts
  template:
    src: TrustedHosts.j2
    dest: /etc/dkimkeys/TrustedHosts
    owner: root
    group: root
    mode: '0644'
  notify: Restart opendkim

- name: Enable and start OpenDKIM service
  service:
    name: opendkim
    enabled: true
    state: started
