---
- name: Remove sysctl kernel hardening settings (without reload)
  sysctl:
    name: "{{ param }}"
    state: absent
    reload: false
  loop:
    - kernel.kptr_restrict
    - kernel.unprivileged_bpf_disabled
    - net.ipv4.conf.default.accept_source_route
    - net.ipv4.conf.default.accept_redirects
    - net.ipv4.conf.default.send_redirects
    - net.ipv4.conf.default.rp_filter
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  loop_control:
    loop_var: param

- name: Remove kernel.modules_disabled from config files
  shell: "sed -i '/^kernel\\.modules_disabled/d' {{ path }}"
  with_fileglob:
    - /etc/sysctl.conf
    - /etc/sysctl.d/*.conf
  loop_control:
    loop_var: path
  ignore_errors: true

- name: Disable usb-storage kernel module
  copy:
    dest: /etc/modprobe.d/usb-storage.conf
    content: |
      install usb-storage /bin/true
    owner: root
    group: root
    mode: '0644'

- name: Install USBGuard
  apt:
    name: usbguard
    state: present

- name: Enable and start USBGuard
  systemd:
    name: usbguard
    enabled: true
    state: started
