---
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Remove legacy rng-tools and rng-tools-debian (not usable on this system)
  ansible.builtin.apt:
    name:
      - rng-tools
      - rng-tools-debian
    state: absent

- name: Disable legacy rng-tools service if it exists
  ansible.builtin.systemd:
    name: rng-tools
    state: stopped
    enabled: false
  ignore_errors: true

- name: Install jitterentropy-rngd (software entropy daemon)
  ansible.builtin.apt:
    name: jitterentropy-rngd
    state: present

- name: Enable and start jitterentropy-rngd
  ansible.builtin.systemd:
    name: jitterentropy-rngd
    enabled: true
    state: started
