---
- name: Install auditd and supporting plugins
  apt:
    name:
      - auditd
      - audispd-plugins
    state: present
    update_cache: true

- name: Ensure /etc/audit directory exists
  file:
    path: /etc/audit
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy auditd configuration files individually
  copy:
    src: "{{ item }}"
    dest: "/etc/audit/{{ item | basename }}"
    owner: root
    group: root
    mode: '0640'
  with_fileglob:
    - "{{ role_path }}/files/*.conf"
  notify: restart auditd

- name: Enable and start auditd
  systemd:
    name: auditd
    enabled: true
    state: started

- name: Ensure sysstat is installed
  apt:
    name: sysstat
    state: present

- name: Enable data collection in sysstat config
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
  notify: restart sysstat timers

- name: Enable and start sysstat timers
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - sysstat-collect.timer
    - sysstat-summary.timer

- name: Deploy auditd email alert script
  template:
    src: auditd-alert.sh.j2
    dest: /etc/cron.daily/auditd-alert
    owner: root
    group: root
    mode: '0755'
