- name: Install auditd and supporting plugins
  apt:
    name:
      - auditd
      - audispd-plugins
    state: present
    update_cache: true

- name: Ensure /etc/audit directory exists
  file:
    path: /etc/audit
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy auditd configuration
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/audit/
    owner: root
    group: root
    mode: '0640'
    directory_mode: '0755'
  notify: restart auditd
  ignore_errors: false

- name: Enable and start auditd
  systemd:
    name: auditd
    enabled: true
    state: started

- name: Ensure sysstat is installed and enabled
  apt:
    name: sysstat
    state: present

- name: Enable data collection in sysstat config
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
  notify: restart sysstat

- name: Restart sysstat
  systemd:
    name: sysstat
    enabled: true
    state: restarted

- name: Deploy auditd email alert script
  template:
    src: auditd-alert.sh.j2
    dest: /etc/cron.daily/auditd-alert
    owner: root
    group: root
    mode: '0755'
