---
- name: Install AppArmor and required tools
  apt:
    name:
      - apparmor
      - apparmor-utils
    state: present

- name: Enable AppArmor service
  service:
    name: apparmor
    enabled: true
    state: started
