---
- name: Ensure NetworkManager is installed
  apt:
    name: network-manager
    state: present
    update_cache: yes

- name: Enable and start NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Remove iface lines from /etc/network/interfaces (if any)
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^iface .* inet'
    state: absent
  notify: Restart NetworkManager
  when: ansible_facts['distribution'] == 'Debian'

- name: Enable autoconnect for all NetworkManager connections
  shell: |
    nmcli -t -f NAME con show | while read line; do
      nmcli con modify "$line" connection.autoconnect yes
    done
  changed_when: false
