---
- name: Ensure certbot is installed
  apt:
    name: certbot
    state: present
    update_cache: true

- name: Ensure {{ certbot_helpers_dir }} exists
  file:
    path: "{{ certbot_helpers_dir }}"
    state: directory
    mode: '0755'
    owner: dave
    group: dave

# Copy .sh files with executable permissions
- name: Copy certbot.sh
  copy:
    src: certbot.sh
    dest: "{{ certbot_helpers_dir }}/certbot.sh"
    mode: '0755'
    owner: dave
    group: dave

- name: Copy missing.sh
  copy:
    src: missing.sh
    dest: "{{ certbot_helpers_dir }}/missing.sh"
    mode: '0755'
    owner: dave
    group: dave

- name: Run missing.sh to check and issue missing certs
  command: "{{ certbot_helpers_dir }}/missing.sh"
  become: true
  register: missing_sh_result
  changed_when: false
  failed_when: missing_sh_result.rc != 0 and "'✅ No missing domains'" not in missing_sh_result.stdout
  ignore_errors: true

- name: Copy certbot_clean_old.sh
  copy:
    src: certbot_clean_old.sh
    dest: "{{ certbot_helpers_dir }}/certbot_clean_old.sh"
    mode: '0755'
    owner: dave
    group: dave

- name: Run clean_old.sh to check and issue missing certs
  command: "{{ certbot_helpers_dir }}/certbot_clean_old.sh"
  become: true
  changed_when: false
