---
- name: Ensure certbot is installed
  apt:
    name: certbot
    state: present
    update_cache: true

- name: Ensure /home/dave/bin exists
  file:
    path: /home/dave/bin
    state: directory
    mode: '0755'
    owner: dave
    group: dave

# Copy .sh files with executable permissions
- name: Copy certbot.sh
  copy:
    src: certbot.sh
    dest: /home/dave/bin/certbot.sh
    mode: '0755'
    owner: dave
    group: dave

- name: Copy missing.sh
  copy:
    src: missing.sh
    dest: /home/dave/bin/missing.sh
    mode: '0755'
    owner: dave
    group: dave

# Copy .conf files with normal permissions
- name: Copy 001-ashtangayoga.ie-ssl.conf.no-proxy
  copy:
    src: 001-ashtangayoga.ie-ssl.conf.no-proxy
    dest: /home/dave/bin/001-ashtangayoga.ie-ssl.conf.no-proxy
    mode: '0644'
    owner: dave
    group: dave

- name: Copy 001-ashtangayoga.ie-ssl.conf.proxy
  copy:
    src: 001-ashtangayoga.ie-ssl.conf.proxy
    dest: /home/dave/bin/001-ashtangayoga.ie-ssl.conf.proxy
    mode: '0644'
    owner: dave
    group: dave

# Run the missing.sh script
- name: Run missing.sh to check and issue missing certs
  command: /home/dave/bin/missing.sh
  become: true
  register: missing_sh_result
  changed_when: false
  failed_when: missing_sh_result.rc != 0 and "'✅ No missing domains'" not in missing_sh_result.stdout
  ignore_errors: true
