---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true

- name: Run Node Exporter container with systemd collector support
  community.docker.docker_container:
    name: node_exporter
    image: prom/node-exporter:latest
    restart_policy: always
    state: started
    network_mode: host
    pid_mode: host
    privileged: true
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
      - "/run/systemd:/run/systemd:ro"
      - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro"
    command: >
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
      --path.rootfs=/rootfs
      --collector.systemd
      --collector.processes
      --collector.netstat
