---
kernel_params:
  net.ipv4.ip_forward: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.all.log_martians: 1
