logrotate_configs:
  - name: auth
    path: /var/log/auth.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: apache2
    path: /var/log/apache2/*.log
    options: [daily, rotate 14, compress, delaycompress, missingok, notifempty, create 0640 root adm]

  - name: apparmor
    path: /var/log/apparmor/*
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: apt
    path: /var/log/apt/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: audit
    path: /var/log/audit/audit.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: boot
    path: /var/log/boot.log
    options: [monthly, rotate 1, compress, missingok, notifempty]

  - name: clamav
    path: /var/log/clamav/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: cron
    path: /var/log/cron.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: dbconfig-common
    path: /var/log/dbconfig-common/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: dpkg
    path: /var/log/dpkg.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: exim4
    path: /var/log/exim4/*.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: fail2ban
    path: /var/log/fail2ban.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: fontconfig
    path: /var/log/fontconfig.log
    options: [weekly, rotate 2, compress, missingok, notifempty]

  - name: installer
    path: /var/log/installer/syslog
    options: [monthly, rotate 1, compress, missingok, notifempty]

  - name: journal
    path: /var/log/journal/*/*.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: kern
    path: /var/log/kern.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: letsencrypt
    path: /var/log/letsencrypt/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: lynis
    path: /var/log/lynis*.log
    options: [weekly, rotate 2, compress, missingok, notifempty]

  - name: mail
    path: /var/log/mail.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: php-fpm
    path: /var/log/php*.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: privoxy
    path: /var/log/privoxy/logfile
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: rclone
    path: /var/log/rclone-backup.log
    options: [weekly, rotate 2, compress, missingok, notifempty]

  - name: redis
    path: /var/log/redis/redis-server.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: runit
    path: /var/log/runit/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: syslog
    path: /var/log/syslog
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: sysstat
    path: /var/log/sysstat/*
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: unattended-upgrades
    path: /var/log/unattended-upgrades/unattended-upgrades.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: usbguard
    path: /var/log/usbguard/usbguard-audit.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: userlog
    path: /var/log/user.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: webdis
    path: /var/log/webdis/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: wtmp
    path: /var/log/wtmp
    options: [monthly, rotate 1, missingok]

  - name: btmp
    path: /var/log/btmp
    options: [monthly, rotate 1, missingok]

  - name: lastlog
    path: /var/log/lastlog
    options: [monthly, rotate 1, missingok]

  - name: private
    path: /var/log/private/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]
