---
- name: Initialize AIDE database
  ansible.builtin.command: /usr/bin/aide --init --config=/etc/aide/aide.conf
  args:
    creates: /var/lib/aide/aide.db.new.gz

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
