---
- name: Initialize AIDE database
  ansible.builtin.command: /usr/sbin/aide --init
  args:
    creates: /var/lib/aide/aide.db.new.gz

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
