---
- name: Install OpenDMARC
  apt:
    name: opendmarc
    state: present
    update_cache: true

- name: Recursively copy OpenDMARC configuration to /etc
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/
    owner: root
    group: root
    mode: preserve
    directory_mode: '0755'
  notify: Restart opendmarc

- name: Ensure postfix private socket directory for OpenDMARC exists
  file:
    path: /var/spool/postfix/private
    state: directory
    owner: postfix
    group: postfix
    mode: '0777'

- name: Enable and start OpenDMARC service
  service:
    name: opendmarc
    enabled: true
    state: started
