---
role_email: "dmz.oneill@gmail.com"
role_user: "dave"
role_hostname: "feeditout"
role_fqdn: "feeditout.com"
role_ipv4_addr: "185.219.84.242"
role_ipv4_mask: "26"
role_ipv4_gw: "185.219.84.193"
role_ipv4_dns1: "8.8.8.8"
role_ipv4_dns2: "1.1.1.1"
role_ipv6_addr: "2a0d:5940:103:1::2"
role_ipv6_mask: "64"
role_ipv6_gw: "2a0d:5940:103::1"
role_ipv6_dns1: "2606:4700:4700::1111"
role_ipv6_dns2: "2001:4860:4860::8888"

# ansible_pull
is_ansible_pull_host: true
ansible_pull_repo_url: "https://github.com/dmzoneill/ansible-feeditout-com"
ansible_pull_workdir: "/opt/ansible"
ansible_pull_interval_minutes: 30
ansible_pull_expected_ip: "{{ role_ipv4_addr }}"
ansible_pull_email: "{{ role_email }}"

# auditd
auditd_alert_email: "{{ role_email }}"

# certbot
certbot_helpers_dir: "/home/{{ role_user }}/bin"

# chrootkit
chkrootkit_alert_email: "{{ role_email }}"

# cron
cron_user_files:
  - user: "{{ role_user }}"
    src: "{{ role_user }}"
  - user: "root"
    src: "root"

# dns
dns_nameservers:
  - "{{ role_ipv4_dns1 }}"
  - "{{ role_ipv4_dns2 }}"
  - "{{ role_ipv6_dns1 }}"
  - "{{ role_ipv6_dns2 }}"
resolv_conf_path: "/etc/resolv.conf"
resolv_conf_immutable: true
disable_systemd_resolved: true

# network-manager
network_manager_id: "static-ansible"
network_manager_uuid: "d88f15bb-51d6-401e-9a1c-d1e4e6d5cdbf"
network_manager_type: "ethernet"
network_manager_interface_name: "eth0"
network_manager_ipv4_address1: "{{ role_ipv4_addr }}/{{ role_ipv4_mask }},{{ role_ipv4_gw }}"
network_manager_ipv4_dns: "{{ role_ipv4_dns1 }};{{ role_ipv4_dns2 }}"
network_manager_ipv6_address1: "{{ role_ipv6_addr }}/{{ role_ipv6_mask }}"
network_manager_ipv6_gateway1: "{{ role_ipv6_gw }}"
network_manager_ipv6_dns: "{{ role_ipv6_dns1 }};{{ role_ipv6_dns2 }}"

# passwd
users:
  - name: "tim"
  - name: "eunice"

# sudo
sudo_user: "{{ role_user }}"
sudo_commands: "ALL"

# php-fpm
php_fpm_package: "php8.2-fpm"
php_fpm_mysql_package: "php8.2-mysql"
php_fpm_service: "php8.2-fpm"
php_fpm_conf_dir: "/etc/php/8.2/fpm"
php_fpm_conf_file: "{{ php_fpm_conf_dir }}/php-fpm.conf"
php_fpm_pool_file: "{{ php_fpm_conf_dir }}/pool.d/www.conf"

# fail2ban
fail2ban_jail: "sshd"
unban_ips:
  - "119.15.95.38"

# saslauthd
saslauthd_mechanism: "pam"
saslauthd_threads: 5
saslauthd_options: "-c -m /var/spool/postfix/var/run/saslauthd"

# services
disable_services:
  - "cyrus-imapd.service"
  - "geoclue.service"
  - "iio-sensor-proxy.service"
  - "lynis.service"
  - "man-db.service"
  - "packagekit.service"
  - "packagekit-offline-update.service"
  - "wpa_supplicant.service"

# hostname
hostname: "{{ role_hostname }}"
fqdn: "{{ role_fqdn }}"
loopback_ip: "127.0.1.1"
domain: "{{ role_fqdn }}"

# iptables
iptables_rules_file: "rules.v4"
iptables_rules_path: "/etc/iptables/rules.v4"
ip6tables_rules_file: "rules.v6"
ip6tables_rules_path: "/etc/iptables/rules.v6"

# kernel
kernel_params:
  net.ipv4.ip_forward: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.all.log_martians: 1

# locale
locale_timezone: "Europe/Dublin"
locale_zonefile: "/usr/share/zoneinfo/Europe/Dublin"
locale_lang: "en_IE.UTF-8"
locale_language: "en_IE:en"
locale_lc_all: "en_IE.UTF-8"

# logwatch
logwatch_mailto: "{{ role_email }}"
logwatch_detail: "High"
logwatch_range: "yesterday"
logwatch_output: "mail"

# ntp
ntp_timezone: "Europe/Dublin"
ntp_package: "chrony"
ntp_service: "chrony"

# apache
broken_apache_modules:
  - name: mpm_prefork
    package: null
  - name: qos
    package: libapache2-mod-qos
  - name: evasive
    package: libapache2-mod-evasive
  - name: php
    package: libapache2-mod-php8.2
  - name: php8.2
    package: libapache2-mod-php8.2
  - name: security2
    package: libapache2-mod-security2
required_apache_modules:
  - name: headers
    package: apache2
  - name: mpm_event
    package: apache2
  - name: proxy
    package: apache2
  - name: proxy_fcgi
    package: apache2
  - name: setenvif
    package: apache2
  - name: geoip
    package: libapache2-mod-geoip
  - name: fcgid
    package: libapache2-mod-fcgid

# postfix
mailname: "{{ role_fqdn }}"
mail_domains:
  - "ashtangayoga.ie"
  - "ecu-emr.com"
  - "{{ role_fqdn }}"
  - "feeditout.site"
  - "feeditout.xyz"
  - "fio.ie"
  - "yogamantra.com"
mail_main_tls_cert: "/etc/letsencrypt/live/{{ role_fqdn }}/fullchain.pem"
mail_main_tls_key: "/etc/letsencrypt/live/{{ role_fqdn }}/privkey.pem"

virtualaliases:
  - alias: "# Explicit mapping for postmaster with/without trailing dot"
    recipient: ""
  - alias: "postmaster@{{ role_fqdn }}"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "postmaster@{{ role_fqdn }}."
    recipient: "{{ role_user }}, {{ role_email }}"

  - alias: "# Ayc"
    recipient: ""
  - alias: "info@ashtangayoga.ie"
    recipient: "cu.eunice@gmail.com, {{ role_email }}"
  - alias: "eunice@ashtangayoga.ie"
    recipient: "cu.eunice@gmail.com, {{ role_email }}"

  - alias: "# Tim"
    recipient: ""
  - alias: "tim@feeditout.com"
    recipient: "{{ role_user }}, tim, feeditout@gmail.com, {{ role_email }}"
  - alias: "tim@fio.ie"
    recipient: "{{ role_user }}, tim, feeditout@gmail.com, {{ role_email }}"
  - alias: "feeditout@feeditout.com"
    recipient: "{{ role_user }}, tim, feeditout@gmail.com, {{ role_email }}"
  - alias: "feeditout@fio.ie"
    recipient: "{{ role_user }}, tim, feeditout@gmail.com, {{ role_email }}"

  - alias: "# {{ role_user }}"
    recipient: ""
  - alias: "{{ role_user }}@feeditout.com"
    recipient: "{{ role_user }}, {{ role_email }}"

  - alias: "# Catch all"
    recipient: ""
  - alias: "@feeditout.site"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "@feeditout.xyz"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "@feeditout.com"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "@ashtangayoga.ie"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "@yogamantra.com"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "@ecu-emr.com"
    recipient: "{{ role_user }}, {{ role_email }}"
  - alias: "@fio.ie"
    recipient: "{{ role_user }}, {{ role_email }}"


domains:
  - domain: fio.ie
    document_root: feeditout.com
    virtual_hosts:
      - name: www.fio.ie
        document_root: feeditout.com
        enabled: true
      - name: home.fio.ie
        document_root: feeditout.com
        enabled: true
      - name: cv.fio.ie
        document_root: cv.fio.ie
        enabled: true
      - name: pma.fio.ie
        document_root: phpmyadmin
        enabled: true
    loglevel: debug
    enabled: true

  - domain: feeditout.xyz
    document_root: feeditout.xyz
    virtual_hosts:
      - name: www.feeditout.xyz
        document_root: feeditout.xyz
        enabled: true
    loglevel: debug
    enabled: true

  - domain: feeditout.site
    document_root: feeditout.site
    virtual_hosts:
      - name: www.feeditout.site
        document_root: feeditout.site
        enabled: true
    loglevel: debug
    enabled: true

  - domain: feeditout.com
    document_root: feeditout.com
    virtual_hosts:
      - name: www.feeditout.com
        document_root: feeditout.com
        enabled: true
      - name: mta-sts.feeditout.com
        document_root: feeditout.com
        enabled: true
      - name: home.feeditout.com
        document_root: feeditout.com
        enable: true
      - name: cv.feeditout.com
        document_root: cv.fio.ie
        enabled: true
      - name: pma.feeditout.com
        document_root: phpmyadmin
        enabled: true
    loglevel: debug
    enabled: true

  - domain: ecu-emr.com
    document_root: ecu-emr.com
    virtual_hosts:
      - name: www.ecu-emr.com
        document_root: ecu-emr.com
        enabled: true
    custom_directory_perms: true
    loglevel: debug
    enabled: true

  - domain: ashtangayoga.ie
    document_root: ashtangayoga.ie
    virtual_hosts:
      - name: www.ashtangayoga.ie
        document_root: ashtangayoga.ie
        enabled: true
    loglevel: debug
    enabled: true

# logrotate
logrotate_configs:
  - name: auth
    path: /var/log/auth.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: apache2
    path: /var/log/apache2/*.log
    options: [daily, rotate 14, compress, delaycompress, missingok, notifempty, create 0640 root adm]

  - name: apparmor
    path: /var/log/apparmor/*
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: apt
    path: /var/log/apt/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: audit
    path: /var/log/audit/audit.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: boot
    path: /var/log/boot.log
    options: [monthly, rotate 1, compress, missingok, notifempty]

  - name: clamav
    path: /var/log/clamav/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: cron
    path: /var/log/cron.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: dbconfig-common
    path: /var/log/dbconfig-common/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: dpkg
    path: /var/log/dpkg.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: exim4
    path: /var/log/exim4/*.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: fail2ban
    path: /var/log/fail2ban.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: fontconfig
    path: /var/log/fontconfig.log
    options: [weekly, rotate 2, compress, missingok, notifempty]

  - name: installer
    path: /var/log/installer/syslog
    options: [monthly, rotate 1, compress, missingok, notifempty]

  - name: journal
    path: /var/log/journal/*/*.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: kern
    path: /var/log/kern.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: letsencrypt
    path: /var/log/letsencrypt/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: lynis
    path: /var/log/lynis*.log
    options: [weekly, rotate 2, compress, missingok, notifempty]

  - name: mail
    path: /var/log/mail.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: php-fpm
    path: /var/log/php*.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: privoxy
    path: /var/log/privoxy/logfile
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: rclone
    path: /var/log/rclone-backup.log
    options: [weekly, rotate 2, compress, missingok, notifempty]

  - name: redis
    path: /var/log/redis/redis-server.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: runit
    path: /var/log/runit/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: syslog
    path: /var/log/syslog
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: sysstat
    path: /var/log/sysstat/*
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: unattended-upgrades
    path: /var/log/unattended-upgrades/unattended-upgrades.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: usbguard
    path: /var/log/usbguard/usbguard-audit.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: userlog
    path: /var/log/user.log
    options: [daily, rotate 7, compress, missingok, notifempty]

  - name: webdis
    path: /var/log/webdis/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]

  - name: wtmp
    path: /var/log/wtmp
    options: [monthly, rotate 1, missingok]

  - name: btmp
    path: /var/log/btmp
    options: [monthly, rotate 1, missingok]

  - name: lastlog
    path: /var/log/lastlog
    options: [monthly, rotate 1, missingok]

  - name: private
    path: /var/log/private/*.log
    options: [weekly, rotate 4, compress, missingok, notifempty]
