---
- name: Copy Ansible vault password to /etc/ansible
  hosts: new
  become: true
  gather_facts: true
  vars_files:
    - ../host_vars/new.yml

  tasks:
    - name: Ensure /etc/ansible directory exists
      file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy vault password file to /etc/ansible/.vault_pass.txt
      copy:
        src: /home/daoneill/.ansible-vault-pass
        dest: /etc/ansible/.vault_pass.txt
        owner: root
        group: root
        mode: '0600'
