---
- name: Ensure Ansible is installed
  package:
    name: ansible
    state: present

- name: Create workdir for ansible-pull
  file:
    path: "{{ ansible_pull_workdir }}"
    state: directory
    mode: '0755'

- name: Clone ansible-pull repo if not present
  git:
    repo: "{{ ansible_pull_repo_url }}"
    dest: "{{ ansible_pull_workdir }}"
    update: true

- name: Deploy ansible-pull systemd service
  template:
    src: ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service
    mode: '0644'

- name: Deploy ansible-pull systemd timer
  template:
    src: ansible-pull.timer.j2
    dest: /etc/systemd/system/ansible-pull.timer
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start ansible-pull timer
  systemd:
    name: ansible-pull.timer
    enabled: true
    state: started
