---
- name: Get existing GRUB_CMDLINE_LINUX value
  shell: |
    grep '^GRUB_CMDLINE_LINUX=' /etc/default/grub | sed -E 's/^GRUB_CMDLINE_LINUX=["'\''](.*)["'\'']/\1/'
  register: grub_cmdline_raw
  changed_when: false
  failed_when: false

- name: Set default value if not found
  set_fact:
    grub_cmdline: "{{ grub_cmdline_raw.stdout | default('') }}"

- name: Build updated GRUB_CMDLINE_LINUX with tty0 and without ttyS0
  set_fact:
    updated_cmdline: >-
      {{
        (
          (grub_cmdline.split() | difference(['console=ttyS0', 'console=ttyS0,115200']) | union(['console=tty0']))
          | unique
        ) | join(' ')
      }}

- name: Update GRUB_CMDLINE_LINUX in /etc/default/grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ updated_cmdline }}"'
    backup: yes
  register: grub_line

- name: Run update-grub to apply changes
  command: update-grub
  when: grub_line.changed
