---
- name: Ensure sulogin password is not enforced
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^SULOGIN_FORCE='
    state: absent

- name: Get existing GRUB_CMDLINE_LINUX value
  shell: |
    grep '^GRUB_CMDLINE_LINUX=' /etc/default/grub | sed -E 's/^GRUB_CMDLINE_LINUX=["'\''"]?(.*?)["'\''"]?$/\1/'
  register: grub_cmdline_raw
  changed_when: false
  failed_when: false

- name: Set default value if not found
  set_fact:
    grub_cmdline: "{{ grub_cmdline_raw.stdout | default('') }}"

- name: Build updated GRUB_CMDLINE_LINUX with tty0 and ttyS0, without quiet
  set_fact:
    updated_cmdline: >-
      {{
        (
          (grub_cmdline + ' ')
          .replace('quiet ', '')
          .replace('console=ttyS0,115200 ', '')
          .replace('console=ttyS0 ', '')
          .replace('console=tty0 ', '')
          .strip()
          .split()
          + ['console=tty0', 'console=ttyS0,115200']
        ) | unique | join(' ')
      }}

- name: Add kernel flag to make random non-blocking (if not present)
  set_fact:
    updated_cmdline: "{{ updated_cmdline + ' random.trust_cpu=on' }}"
  when: "'random.trust_cpu=on' not in updated_cmdline"

- name: Update GRUB_CMDLINE_LINUX in /etc/default/grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ updated_cmdline }}"'
    backup: true
  register: grub_line

- name: Ensure GRUB_TIMEOUT is set to 120 seconds
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=120'
    create: yes
  register: grub_timeout_line

- name: Run update-grub to apply changes
  command: update-grub
  when: grub_line.changed or grub_timeout_line.changed

- name: Reboot system if grub was updated
  reboot:
    msg: "Rebooting to apply GRUB changes"
    pre_reboot_delay: 5
  when: grub_line.changed or grub_timeout_line.changed
