---
- name: Install OpenVPN
  apt:
    name: openvpn
    state: present

- name: Ensure /etc/openvpn directory exists
  file:
    path: /etc/openvpn
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure OpenVPN service is enabled
  systemd:
    name: openvpn
    enabled: true
