---
- name: Load package list from file
  set_fact:
    package_list: "{{ lookup('file', '../files/package-list.txt').splitlines() }}"
    batch_size: 20

- name: Split package list into batches
  set_fact:
    package_batches: "{{ package_list | batch(batch_size) }}"

- name: Temporarily disable perlindex
  copy:
    dest: /usr/local/bin/perlindex
    content: "#!/bin/sh\nexit 0"
    mode: '0755'

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install each batch (ignoring missing packages)
  become: true
  shell: |
    echo "Installing batch {{ batch_index + 1 }} of {{ package_batches | length }}"
    PATH="/usr/local/bin:$PATH" DEBIAN_FRONTEND=noninteractive apt-get install -y --ignore-missing {{ item | join(' ') }}
  loop: "{{ package_batches }}"
  loop_control:
    index_var: batch_index
    label: "Batch {{ batch_index + 1 }}"
  register: install_results
  changed_when: false

- name: Remove perlindex override
  file:
    path: /usr/local/bin/perlindex
    state: absent

- name: Show summary of batch install results
  debug:
    msg: |
      Completed {{ package_batches | length }} batches.
      Please review stdout/stderr of any failed batches if needed.
